# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getlist.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgetlist.proto\x12\x07getlist\"\x1e\n\x0eGetListRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\"=\n\x0fGetListResponse\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0f\n\x07\x41\x64\x64ress\x18\x02 \x01(\t\x12\x0b\n\x03\x41ge\x18\x03 \x01(\t2N\n\x0eGetListService\x12<\n\x07GetList\x12\x17.getlist.GetListRequest\x1a\x18.getlist.GetListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'getlist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLISTREQUEST']._serialized_start=26
  _globals['_GETLISTREQUEST']._serialized_end=56
  _globals['_GETLISTRESPONSE']._serialized_start=58
  _globals['_GETLISTRESPONSE']._serialized_end=119
  _globals['_GETLISTSERVICE']._serialized_start=121
  _globals['_GETLISTSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
